services:
  accountservice.webapi:
    image: ${DOCKER_REGISTRY-}accountservicewebapi
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    container_name: account-api
    build:
      context: .
      dockerfile: AccountService/Hosts/AccountService.WebAPI/Dockerfile
    ports:
      - "19001:8081"

  identityservice.webapi:
    image: ${DOCKER_REGISTRY-}identityservicewebapi
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    container_name: identity-api
    build:
      context: .
      dockerfile: IdentityService/Hosts/IdentityService.WebAPI/Dockerfile
    ports:
      - "18001:8081"

